%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: Results/chair_moves_and_tr_gramian5.txt
%
% Auto-generated by MATLAB on 11-Sep-2021 15:04:36

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["m_bar", "m_std", "m_max", "tr", "m_bar1", "m_std1", "m_max1", "tr1"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
path=pwd;
filename="chair_moves_and_tr_gramian5.txt";
sim = readtable(strcat(path,"/",filename), opts);

m_bar=(sim.m_bar+sim.m_bar1)/2;

%% Clear temporary variables
clear opts
