
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: ./single_layer_asym_seed_gramian2.txt
%
% Auto-generated by MATLAB on 24-Sep-2021 16:13:51
%figure('units','pixels', 'outerposition', [135,204,1570,659])
for data=1:6
% 1 - 3 x 3
% 2 - 5 x 5
% 3 - asym bottom 
% 4 - asym second

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 12);

% Specify range and delimiter
switch data 
    case 1
        opts.DataLines = [1, 3];
    case 2
        opts.DataLines = [1, 5];
    case {3,4,5,6}
        opts.DataLines = [1, Inf];
end
    
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["m_bar", "m_std", "m_max", "betweenness", "closeness", "eigenvector", "mineig", "pgrank", "tr", "SeedX", "SeedY", "seed_label"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

path_to_file="./";

switch data 
    case 1
        filename="single_layer_square_metrics_3b3.txt";
    case 2
        filename="single_layer_square_metrics_5b5.txt";
    case 3
        filename="single_layer_square_metrics_10b10.txt";
    case 4
        filename="single_layer_square_metrics_20b20.txt";
    case 5
        filename="single_layer_asym_metrics_bottom.txt";
    case 6
        filename="single_layer_asym_metrics_second.txt";
end

file_path=strcat(path_to_file,filename);

% Import the data
metrics = readtable(file_path, opts);


switch data 
    case 1
        %nmvo 5b5
        metrics.nmov = [6.44; 6.55; 6.44 ];
    case {2,3,4}
        metrics.nmov=metrics.m_bar;
    case 5
        %nmov bottom asym 
        metrics.nmov=[11.81; 12.04; 12.18; 12.11; 11.96; 12.30; 12.18; 12.41; 12.33; 12.70; 12.44; 11.78; 12.22; 12.44; 12.59; 12.15];
    case 6
        %nmov second asym 
        metrics.nmov=[11.19;11.81;11.68;11.44; 11.56; 12.19;12.44 ;12.19 ;11.50;12.25 ; 11.75 ;11.25 ;10.56 ; 11.69; 10.31];
end



%% Clear temporary variables
clear opts

%% Plotting
% subplot(2,3,data)
% c = polyfit(metrics.tr,metrics.nmov,1);
% y_est = polyval(c,metrics.tr);
% hold on
% plot(metrics.tr,y_est,'b-','LineWidth',1)
% plot(metrics.tr,metrics.nmov,'r*','Markersize',8)
% hold off
% grid on
% legend('Trend line', 'Computed data','Location', 'Southeast')
% 
% switch data 
%     case 1
%         title('3 x 3 shape')
%     case 2
%         title('5 x 5 shape')
%     case 3
%         title('10 x 10 shape')
%     case 4
%         title('20 x 20 shape')
%     case 5
%         title('Asymmetrical, Fig. 7e bottom layer')
%     case 6
%         title('Asymmetrical, Fig. 7e second layer')
% end
% 
% xlabel('$trace(W_{H,T})$', 'Interpreter', 'latex','FontSize',12)
% ylabel('$\bar{m}$', 'Interpreter', 'latex','FontSize',12)
% 
% ax=gca;
% ax.FontSize=10;

close all

figure('units','pixels','outerposition',[1921,1018,1280,583])
% close all

subplot(2,3,1); plot(metrics.tr,metrics.nmov,'rx'); title('trace(Wc)'); grid on;
subplot(2,3,2); plot(metrics.betweenness,metrics.nmov,'rx');title('betweenness'); grid on;
subplot(2,3,3); plot(metrics.closeness,metrics.nmov,'rx');title('closeness');  grid on;
subplot(2,3,4); plot(metrics.eigenvector,metrics.nmov,'rx');title('eigenvector');  grid on;
subplot(2,3,5); plot(metrics.mineig,metrics.nmov,'rx');title('mineig');  grid on;
subplot(2,3,6); plot(metrics.pgrank,metrics.nmov,'rx');title('pgrank');  grid on;


fname_str=strsplit(filename,'.');

ax=gcf;
exportgraphics(ax, strcat(fname_str(1),'.png'),'Resolution',300)
end