
%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: ./single_layer_asym_seed_gramian2.txt
%
% Auto-generated by MATLAB on 24-Sep-2021 16:13:51
close all
data=1;
% 1 - asym
% 2 - chair


%% Setup the Import Options and import the NUMBER OF MOV.
%This first part is just to extract the number of movements. I only ran my algorithm once, because it takes too long
%all other files will have just the metrics
if data == 1
    opts = delimitedTextImportOptions("NumVariables", 10);

    % Specify range and delimiter
    opts.DataLines = [2, Inf];
    opts.Delimiter = " ";

    % --- asym structure --
    % Specify column names and types
    opts.VariableNames = ["m_bar", "Var2", "Var3", "Var4", "Var5", "m_bar1", "Var7", "Var8", "Var9", "Var10"];
    opts.SelectedVariableNames = ["m_bar", "m_bar1"];
    opts.VariableTypes = ["double", "string", "string", "string", "string", "double", "string", "string", "string", "string"];

    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";
    opts.ConsecutiveDelimitersRule = "join";
    opts.LeadingDelimitersRule = "ignore";

    % Specify variable properties
    opts = setvaropts(opts, ["Var2", "Var3", "Var4", "Var5", "Var7", "Var8", "Var9", "Var10"], "WhitespaceRule", "preserve");
    opts = setvaropts(opts, ["Var2", "Var3", "Var4", "Var5", "Var7", "Var8", "Var9", "Var10"], "EmptyFieldRule", "auto");

    file_name="asym_moves.txt";
else
    opts = delimitedTextImportOptions("NumVariables", 25);

    % Specify range and delimiter
    opts.DataLines = [2, Inf];
    opts.Delimiter = " ";

    % Specify column names and types
    opts.VariableNames = ["m_bar", "m_std", "m_max", "tr1", "tr2", "mineig1", "mineig2", "pgrank1", "eigenvector1", "closeness1", "betweenness1", "tr3", "tr4", "mineig3", "mineig4", "pgrank2", "eigenvector2", "closeness2", "betweenness2", "seedl1", "seedl2", "seedl3", "seedl4", "seedl5", "seedl6"];
    opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

    % Specify file level properties
    opts.ExtraColumnsRule = "ignore";
    opts.EmptyLineRule = "read";
    opts.ConsecutiveDelimitersRule = "join";
    opts.LeadingDelimitersRule = "ignore";
    file_name="chair_moves.txt";
end

file_path="../Results/";
% Import the data
metrics_with_mbar = readtable(strcat(file_path,file_name), opts);
% Clear temporary variables
clear opts


%% Setup the Import Options and import the data
if data == 1
    opts = delimitedTextImportOptions("NumVariables", 23);
else
    opts = delimitedTextImportOptions("NumVariables", 25);
end

% Specify range and delimiter
opts.DataLines = [1, Inf];
    
opts.Delimiter = " ";

if data==1

    % Specify column names and types
    opts.VariableNames = ["m_bar", "m_std", "m_max",...
                        "tr1", "tr2", "mineig1", "mineig2", "pgrank1", "eigenvector1", "closeness1", "betweenness1",...
                        "tr3", "tr4", "mineig3", "mineig4", "pgrank2", "eigenvector2", "closeness2", "betweenness2",...
                        "Seedl1", "Seedl2", "Seedl3", "Seedl4"];
    opts.VariableTypes = ["double", "double", "double",...
                        "double", "double", "double", "double", "double","double", "double", "double",...
                        "double", "double", "double", "double", "double","double", "double", "double",...
                        "double", "double", "double", "double"];
 
else
    
    opts.VariableNames = ["m_bar", "m_std", "m_max",...
                        "tr1", "tr2", "mineig1", "mineig2", "pgrank1", "eigenvector1", "closeness1", "betweenness1",...
                        "tr3", "tr4", "mineig3", "mineig4", "pgrank2", "eigenvector2", "closeness2", "betweenness2",...
                        "Seedl1", "Seedl2", "Seedl3", "Seedl4", "Seedl5", "Seedl6"];
    opts.VariableTypes = ["double", "double", "double",...
                        "double", "double", "double", "double", "double","double", "double", "double",...
                        "double", "double", "double", "double", "double","double", "double", "double",...
                        "double", "double", "double", "double", "double", "double"];
                    
end

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

path_to_file="../Results/";

switch data 
    case 1
        filename="asym_metrics_weighted_notmean.txt";
    case 2
        filename='chair_moves_and_tr_gramian_weighted_notmean.txt';
end

file_path=strcat(path_to_file,filename);

% Import the data
metrics = readtable(file_path, opts);

% metrics.nmov = (asymmovesandtrgramian1.m_bar+asymmovesandtrgramian1.m_bar1)/2;

metrics.nmov = metrics_with_mbar.m_bar;

%% Clear temporary variables
clear opts

%% Plot
close all

figure
subplot(8,2,1); plot(metrics.tr1,metrics.nmov,'rx'); title('trace(Wc) A-MD, B-s1'); grid on;
subplot(8,2,3); plot(metrics.tr2,metrics.nmov,'rx'); title('trace(Wc) A-MD, B-all'); grid on;

subplot(8,2,2); plot(abs(metrics.tr3*10^-42),metrics.nmov,'rx'); title('trace(Wc) A-1/MD, B-s1'); grid on;
subplot(8,2,4); plot(abs(metrics.tr4*10^-42),metrics.nmov,'rx'); title('trace(Wc) A-1/MD, B-all'); grid on;

subplot(8,2,5); plot(metrics.mineig1,metrics.nmov,'rx'); title('mineig(Wc) A-MD, B-s1'); grid on;
subplot(8,2,7); plot(metrics.mineig2,metrics.nmov,'rx'); title('mineig(Wc) A-MD, B-all'); grid on;

subplot(8,2,6); plot(metrics.mineig3,metrics.nmov,'rx'); title('mineig(Wc) A-1/MD, B-s1'); grid on;
subplot(8,2,8); plot(metrics.mineig4,metrics.nmov,'rx'); title('mineig(Wc) A-1/MD, B-all'); grid on;

subplot(8,2,9); plot(metrics.betweenness1,metrics.nmov,'rx');title('betweenness A-MD'); grid on;
subplot(8,2,10); plot(metrics.betweenness2,metrics.nmov,'rx');title('betweenness A-1/MD'); grid on;

subplot(8,2,11); plot(metrics.closeness1,metrics.nmov,'rx');title('closeness A-MD');  grid on;
subplot(8,2,12); plot(metrics.closeness2,metrics.nmov,'rx');title('closeness A-1/MD');  grid on;

subplot(8,2,13); plot(metrics.eigenvector1,metrics.nmov,'rx');title('eigenvector A-MD');  grid on;
subplot(8,2,14); plot(metrics.eigenvector2,metrics.nmov,'rx');title('eigenvector A-1/MD');  grid on;

subplot(8,2,15); plot(metrics.pgrank1,metrics.nmov,'rx');title('pgrank A-MD');  grid on;
subplot(8,2,16); plot(metrics.pgrank2,metrics.nmov,'rx');title('pgrank A-1/MD');  grid on;

% tr3=abs(metrics.tr3*10^-42);
% for i=1:length(tr3)
%     tr(i)=round(tr3(i)*1000)/1000;
% end
% 
% figure('units', 'pixels', 'outerposition', [1960,831,1188,759])
% subplot(2,2,1); plot(tr3,metrics.nmov,'rx'); title('trace(Wc$-1$) A-1/MD, B-s1'); grid on;
% subplot(2,2,3); boxplot(metrics.nmov,tr); title('trace(Wc$-1$) A-1/MD, B-s1');  grid on;
% 
% tr4=abs(metrics.tr4*10^-42);
% for i=1:length(tr4)
%     tr(i)=round(tr4(i)*1000)/1000;
% end
% subplot(2,2,2); plot(tr3,metrics.nmov,'rx'); title('trace(Wc$-1$) A-1/MD, B-all'); grid on;
% subplot(2,2,4); boxplot(metrics.nmov,tr); title('trace(Wc$-1$) A-1/MD, B-all');  grid on;;

pause(0.5)
figure('units', 'pixels', 'outerposition', [1960,831,1188,759])
subplot(2,2,1); plot(metrics.closeness1,metrics.nmov,'rx');title('closeness A-MD');  grid on;
clness=metrics.closeness1;
for i=1:length(metrics.closeness1)
    if data==1
        clness(i)=round(metrics.closeness1(i)*(10^3)*5)/5; %5 for asym, 10 for chair
    else
        clness(i)=round(metrics.closeness1(i)*(10^3)*10)/10; %5 for asym, 10 for chair
    end
end

subplot(2,2,2); boxplot(metrics.nmov,clness);title('closeness A-MD');  grid on;
xtickangle(45);

subplot(2,2,3); plot(metrics.tr4,metrics.nmov,'rx'); title('trace(Wc$-1$) A-1/MD, B-all'); grid on;
tr=metrics.tr4;
for i=1:length(metrics.tr4)
    tr(i)=round(metrics.tr4(i)*100)/100;
end
subplot(2,2,4); boxplot(metrics.nmov,tr); title('trace(Wc$-1$) A-1/MD, B-all');  grid on;
xtickangle(45);

% ax=gcf;
% fname_str=strsplit(filename,'.');
% exportgraphics(ax, strcat(char(fname_str(1)), '_TRACE_CLOSENESS_' ,'.png'),'Resolution',300)

pause(0.5)
figure('units', 'pixels', 'outerposition', [1960,831,1500,500])
subplot(1,2,1); boxplot(metrics.nmov,clness); 
title('Closeness')
xlabel('$c(s_1)$', 'Interpreter', 'latex');  grid on;
% ylabel('$\bar{m}$', 'Interpreter', 'latex')
ylabel('$\mu_{m}$', 'Interpreter', 'latex') % 2
ax=gca;
ax.FontSize=14;
ax.XLabel.FontSize=20;
ax.YLabel.FontSize=20;
xtickangle(45);
subplot(1,2,2); boxplot(metrics.nmov,tr); 
title('NCG')
xlabel('$\tau$', 'Interpreter', 'latex');  grid on;
% ylabel('$\bar{m}$', 'Interpreter', 'latex');
ylabel('$\mu_{m}$', 'Interpreter', 'latex'); %2
xtickangle(45);
ax=gca;
ax.FontSize=14;
ax.XLabel.FontSize=20;
ax.YLabel.FontSize=20;

ax=gcf;
fname_str=strsplit(filename,'.');
% exportgraphics(ax, strcat(char(fname_str(1)), '_TRACE_CLOSENESS_' ,'.png'),'Resolution',300)
% exportgraphics(ax, strcat(char(fname_str(1)), '_TRACE_CLOSENESS_2' ,'.png'),'Resolution',300) ; %using \mu

% figure
% % close all
% 
% subplot(3,3,1); plot(metrics.tr3,metrics.nmov,'rx'); title('trace(Wc)'); grid on;
% subplot(3,3,2); plot(metrics.betweenness2,metrics.nmov,'rx');title('betweenness'); grid on;
% subplot(3,3,3); plot(metrics.closeness2,metrics.nmov,'rx');title('closeness');  grid on;
% subplot(3,3,4); plot(metrics.eigenvector2,metrics.nmov,'rx');title('eigenvector');  grid on;
% subplot(3,3,5); plot(metrics.mineig3,metrics.nmov,'rx');title('mineig');  grid on;
% subplot(3,3,6); plot(metrics.pgrank2,metrics.nmov,'rx');title('pgrank');  grid on;
